TOPICS: dict[str, list[str]] = {
    "Sports": [
        "The history of football/soccer in Spain and Latin America",
        "The upcoming Olympics and which sports are most popular",
        "Whether esports should be considered real sports",
        "The most legendary soccer players from Spanish-speaking countries",
        "Weekend sports and staying active",
        "The passion of fans at live sporting events",
        "Swimming, cycling, and outdoor sports culture",
        "Famous tennis players from Spain like Rafael Nadal",
        "The World Cup and its impact on different countries",
        "Running marathons and fitness trends",
    ],
    "Tech": [
        "How smartphones have changed daily life",
        "Space exploration and recent missions",
        "AI and robots in everyday life",
        "Social media and how people communicate",
        "Video games and gaming culture",
        "Electric vehicles and the future of transportation",
        "Streaming services and how we watch content",
        "The rise of remote work and digital nomads",
        "Cybersecurity and staying safe online",
        "3D printing and how it's changing manufacturing",
    ],
    "Movies & TV": [
        "Popular Spanish-language movies and series on Netflix",
        "Favorite movie genres and why",
        "The best movie you've seen recently",
        "Movie snacks and cinema culture around the world",
        "Famous actors from Spanish-speaking countries",
        "Animated movies and their global appeal",
        "True crime documentaries and why people love them",
        "Classic films versus modern blockbusters",
        "How movies portray different cultures",
        "Favorite TV series and what makes them addictive",
    ],
    "Food & Cooking": [
        "Traditional dishes from different Spanish-speaking countries",
        "Your favorite recipe and how to make it",
        "Street food culture in Latin America",
        "Coffee culture around the world",
        "Spicy food — love it or hate it",
        "The best breakfast foods from different cultures",
        "Vegetarian and vegan food trends",
        "Cooking at home versus eating out",
        "Desserts and sweets from Spanish-speaking countries",
        "Food markets and farmers markets",
    ],
    "Travel": [
        "Dream travel destinations in Latin America",
        "Best cities to visit in Spain",
        "Travel tips and packing essentials",
        "Cultural differences when traveling",
        "Beach vs mountains for vacation",
        "Budget travel and finding good deals",
        "Solo travel versus group travel",
        "The most beautiful natural landscapes in the world",
        "Road trips and the freedom of driving",
        "Living abroad and experiencing a new culture",
    ],
    "Science": [
        "Recent discoveries about space and planets",
        "How climate change affects different countries",
        "Interesting animal facts and wildlife conservation",
        "The science of cooking and food chemistry",
        "Volcanoes and earthquakes in Latin America",
        "Ocean exploration and deep sea mysteries",
        "The human brain and how memory works",
        "Renewable energy and the future of power",
        "Medicine and recent breakthroughs in health",
        "Why sleep is so important for our bodies",
    ],
    "Music": [
        "Popular music genres in Spanish-speaking countries",
        "Your favorite song or artist right now",
        "The global rise of reggaeton and Latin pop",
        "Music festivals and live concerts",
        "Learning languages through music and lyrics",
        "How music affects our mood and emotions",
        "Classic rock versus modern pop",
        "Latin jazz and its roots in Cuba",
        "Street musicians and busking culture",
        "The story behind a famous Spanish-language song",
    ],
    "News & Current Events": [
        "An interesting recent news story",
        "Technology trends shaping the future",
        "Environmental news and sustainability efforts",
        "Interesting cultural events happening around the world",
        "New discoveries or inventions",
        "How different countries approach public health",
        "Young people and political engagement",
        "The future of work and automation",
        "Urban development and city planning",
        "International cooperation on global challenges",
    ],
}
